Staging
TOBECHI-GH/Web-ecom-8 pull request #19
Opened 2020-10-19 07:11 UTC by conquext

2020-10-19 18:15 UTC, Oisavictor requested changes
kindly see my comments

2020-10-19 18:15 UTC, Oisavictor commented on server/package.json
> +  "name": "customizr",
shouldn't it be cuztomyz?

2020-10-19 18:15 UTC, Oisavictor commented on src/html/invoice.html
> +    <title>InvoiceS</title>
I think it should be spelt like this "Invoice" and not "InvoiceS"?

2020-10-19 18:15 UTC, Oisavictor commented on src/html/invoice.html
> +            </div>
I suggested that the Payment type shouldn't be text and should be auto generated.
Also Payment date should be auto generated

2020-10-19 18:15 UTC, Oisavictor commented on server/firebase.js
> +};
@conquext why didn't you add the details i sent to you here? for security concerns?

2020-10-19 18:15 UTC, Oisavictor commented on server/README.md
> +  \$ docker run -p 4567:8080 imageId
why did you use port 8080? instead of port 80 as your open port?

2020-10-19 18:15 UTC, Oisavictor commented on dist/invoice.html
> +    <title>InvoiceS</title>
I think you should use "Invoice" instead of "Invoices"

2020-10-19 18:15 UTC, Oisavictor commented on Dockerfile
> +ENV PORT=8080
port 8080? while not port 80?

2020-10-19 18:54 UTC, conquext commented on server/firebase.js
> +};
yeah, it is added in the environment variables

2020-10-19 18:54 UTC, conquext commented on server/README.md
> +  \$ docker run -p 4567:8080 imageId
Port could be any valid address. 8080 is a valid address.

2020-10-19 18:56 UTC, conquext commented on dist/invoice.html
> +    <title>InvoiceS</title>
I merged the code from frontend so i can build a container image to showcase the current build. Comments related to html can be moved under their respective PRs.

2020-10-26 03:59 UTC, Oisavictor approved these changes

2020-10-28 00:17 UTC, TOBECHI-GH approved these changes
Good work

2020-10-28 00:47 UTC, merged