Added preview page
TOBECHI-GH/Web-ecom-8 pull request #26
Opened 2020-10-24 12:59 UTC by RabsonJ

Added preview page

2020-10-24 22:22 UTC, conquext commented
@RabsonJ Please fix all merge conflicts

2020-10-25 09:37 UTC, RabsonJ commented
> @RabsonJ Please fix all merge conflicts

Done

2020-10-25 10:18 UTC, conquext requested changes
Please see comments

2020-10-25 10:18 UTC, conquext commented on dist/preview.html
> +   <link rel="stylesheet" href="./css/index.css">
This href reference will not work with our current setup. All files are compiled by gulp into the dist/folder, so we have to follow the folder structure in the dist/ for all our static assets.

In this case, the correct reference would be 
`   <link rel="stylesheet" href="css/index.css">`

2020-10-25 10:18 UTC, conquext commented on dist/preview.html
> +   const closeOverlay = document.querySelector('.overlay__close').addEventListener('click', () => {
There might be a potential bug here. It is important to check if the querySelector finds the node before attaching an event on it.

**Try something like this instead:**
`   const closeOverlay = document.querySelector('.overlay__close')`
`   if(closeOverlay) closeOverlay.addEventListener('click', () => { ...`

2020-10-25 10:18 UTC, conquext commented on dist/preview.html
> +   const shareInvoice = document.querySelector('.invoice__share').addEventListener('click', () => {
same as closeOverlay above

2020-10-25 10:18 UTC, conquext commented on dist/preview.html
> +   shareInvoice
>>

2020-10-25 10:18 UTC, conquext commented on src/html/preview.html
> +   const closeOverlay = document.querySelector('.overlay__close').addEventListener('click', () => {
Same as above

2020-10-25 10:18 UTC, conquext commented on src/html/preview.html
> +   const shareInvoice = document.querySelector('.invoice__share').addEventListener('click', () => {
Same as above

2020-10-25 10:18 UTC, conquext commented on src/html/preview.html
> +   shareInvoice
Same as above

2020-10-27 08:00 UTC, RabsonJ commented on dist/preview.html
> +   <link rel="stylesheet" href="./css/index.css">
I believe the reference will still work. (./) looks in the current directory (and that's the case here)

2020-10-27 08:04 UTC, RabsonJ commented on dist/preview.html
> +   const closeOverlay = document.querySelector('.overlay__close').addEventListener('click', () => {
This code is supposed to be generated on the server (since we're using **Node.js**) and then sent to the browser. Since we're the ones generating the code on the server, we can be sure that what we're selecting exists.

But I'll change it just to be on the safe side.

Unfortunately I can't test the server code on my machine because it's giving me an error about some gulp file. I don't think Mr Rasheed fixed that. Someone who has the working code will have to put this code in a Node file

2020-10-27 10:36 UTC, conquext commented on dist/preview.html
> +   <link rel="stylesheet" href="./css/index.css">
It will work in development but not in production. In the production build, this is what the directory looks like, at which point, the preview.html can only access the css via `css/index.css` not by `./css/index.css`

2020-10-27 10:41 UTC, conquext commented on dist/preview.html
> +   const closeOverlay = document.querySelector('.overlay__close').addEventListener('click', () => {
The code is not generated on the server, we only serve the static html via nodejs.
Please share the problems you have with gulp on slack so we can take a look at it.

2020-10-27 10:47 UTC, RabsonJ commented on dist/preview.html
> +   const closeOverlay = document.querySelector('.overlay__close').addEventListener('click', () => {
I'm suggesting it should be generated on the server side because we have to insert data from the database into the receipt. If we serve a static file, we'd have to select on the `divs` for the receipt and check if each one of them exists, and the can get messy.

On the other hand if the receipt is dynamically generated we don't have to worry about selecting a bunch of `divs` and checking if each one exists

2020-10-27 10:48 UTC, RabsonJ commented on dist/preview.html
> +   const closeOverlay = document.querySelector('.overlay__close').addEventListener('click', () => {
I'll share a screenshot on slack

2020-10-27 11:08 UTC, conquext commented on dist/preview.html
> +   const closeOverlay = document.querySelector('.overlay__close').addEventListener('click', () => {
You can use template strings to achieve what you describe. The server side don't have access to the dom. It would require a different set of template engine and setups and we wouldn't be using the current work done at all.

2020-10-28 00:50 UTC, merged